# Generated by Django 5.1.5 on 2026-02-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
