# Generated by Django 5.1.3 on 2026-03-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='safety_score',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('GPAY', 'G Pay'), ('CARD', 'Card'), ('WALLET', 'Wallet')], max_length=20),
        ),
    ]
