# Generated by Django 5.1.3 on 2026-03-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixture', '0006_review_safety_score_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprofessional',
            name='service_score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AlterField(
            model_name='serviceprofessional',
            name='safety_score',
            field=models.FloatField(default=5.0),
        ),
    ]
